### ISSUE TITLE
Windows / *.nix import OVAL files save as xccdf

### ISSUE THREAD

**Issue by necrose99** [OpenSCAP/scap-workbench#204]
import OVAL files save as xccdf

as well [Taxii feeds](https://taxiiproject.github.io/about/) to audit against might also be a nicety ..

**Comment by redhatrises** [comment]
OVAL files != XCCDF files. XCCDF files requires additional content and elements which OVAL files do not provide which makes this request not practical. XCCDF is the human readable security guide. OVAL is the file that scans a machine to validate the XCCDF rule. Closing. Feel free to re-open if you feel otherwise.
