### ISSUE TITLE
SCAP for Raspberry Pi OS

### ISSUE THREAD

**Issue by girishkumarbk** [OpenSCAP/scap-workbench#263]
Hi,

How do we get SCAP tools working for Raspberry Pi OS (Buster release) ?

-
Girish BK

**Comment by evgenyz** [comment]
What problem exactly you are experiencing?

**Comment by girishkumarbk** [comment]
There is no selection for vulnerabilities relevant for Raspberry Pi OS.  If you choose Debian or ubuntu ... then most of the scan report ends up in 'Not applicable" 
<img width="819" alt="RaspberryPi-SCAP-Report" src="https://user-images.githubusercontent.com/6768794/84743720-f8791f80-afcf-11ea-8b50-bbcae34772de.png">

**Comment by girishkumarbk** [comment]
Added sample scan report on raspberry pi.

**Comment by ggbecker** [comment]
That's because OpenSCAP identifies `Raspberry Pi OS` as something different than Debian or ubuntu. It would require additional changes to the content which is generated by [github.com/ComplianceAsCode/content](github.com/ComplianceAsCode/content), to include a way to detect `Raspberry Pi OS`. Something like this OVAL check: https://github.com/ComplianceAsCode/content/blob/master/shared/checks/oval/installed_OS_is_debian10.xml#L22

**Comment by evgenyz** [comment]
This proplem is related to the security content, proper place to file an issue is here: https://github.com/ComplianceAsCode/content/issues.
