### ISSUE TITLE
Local Scan Radio Box Disabled

### ISSUE THREAD

**Issue by CSWF4831** [OpenSCAP/scap-workbench#60]
Can't scan localhost due to issue stated in subject line, However Remote Machine (over ssh) radio box is enabled even though SSH is not native to Windows.

Platform: Windows 7 Enterprise x32
SCAP Workbench 1.1.1
Qt 4.8.6
OpenSCAP 1.3.0

**Comment by jan-cerny** [comment]
Hi, unfortunately SCAP Workbench for Windows can scan only remote machines. That's because OpenSCAP does not implement Windows probes. We would love to accept patches that will implement Windows scanning. Currently, the purpose of SCAP Workbench for Windows is only to:
1) perform assessment of a remote Linux server from a Windows computer
2) customize SCAP content using a graphical user interface

**Comment by mpreisler** [comment]
Related to #48
