### ISSUE TITLE
scap-workbench does not ask for privilege elevation

### ISSUE THREAD

**Issue by CEBrooks** [OpenSCAP/scap-workbench#75]
SCAP Workbench 1.1.2 on Fedora 24 -- (VirtualBox 5.1.2 VM)

When running as a "wheel" group member on the X11 GUI console, SCAP Workbench will request privilege elevation ; and once enabled successfully runs all checks.  If I logon via SSH (with X11 forwarding and X11 Trusted) enabled then SCAP Workbench will not ask for privilege elevation and the majority of checks fail on permission errors.

Is there a method to force SCAP Workbench to ask for privileged execution ?

What in the environment does SCAP Workbench use to make the privileged execution decisions ?
That is, can I force it into privileged mode by manipulating the environment.

Yours,
C. E. Brooks
/ceb\

**Comment by WesleyCeraso** [comment]
Hi @CEBrooks, thanks for your report.

The problem you described is due to the lack of a polkit authorization agent when logged though ssh ([see more](https://www.freedesktop.org/software/polkit/docs/0.105/polkit-apps.html)). An workaround I found is to start an agent along with scap-workbench, as follows:
$ scap-workbench; lxpolkit
